spring:
  application:
    name: StudentAnalysis

  profiles:
    active: local

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

app:
  cors:
    allowed-origin: http://localhost:8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: alpha
    display-request-duration: true